export const cardata = {
    "mispar_rechev": "מספר רישוי",
    "kinuy_mishari": "שם דגם",
    "tozeret_nm": "ייצרן",
    "mivchan_acharon_dt": "טסט אחרון",
    "tokef_dt": "תוקף רישיון",
    "achrayut": "אחריות",
    "memuza_kilometer":"ממוצע קילומטר מומלץ לרכב זה ",
    "gil": "גיל הרכב",
    "shnat_yitzur": "שנת ייצור",
    "ahrayut": "אחריות",
    "baalut": "סוג רכב",
    "misgeret": "מספר שלדה",
    "ramat_gimur": "רמת גימור",
    "moed_aliya_lakvish": "מועד עליה לכביש",
    "tozeret_cd": "קוד תוצר",
    "degem_nm": "מספר דגם",
    "tzeva_rechev": "צבע רכב",
    "sug_delek_nm": "סוג דלק",
    "zmig_ahori": "צמיג אחורי",
    "zmig_kidmi": "צמיג קדמי",
    "degem_manoa": "דגם מנוע",
    "kvutzat_zihum": "קבוצת זיהום",
    "ramat_eivzur_betihuty": "רמת איבזור",
    "sug_degem": "סוג דגם",
}